### ISSUE TITLE
Do not bundle dependencies -- use system libraries

### ISSUE THREAD

**Issue by terminus-brut** [fedora-java/javapackages-bootstrap#10]
As a Fedora package maintainer I would like to ask you to consider not bundling your required libraries but rather to use system-provided ones.

I am specifically talking about all of the packages listed in the `project` directory except for `mbi`.

Thank you.

**Comment by mizdebsk** [comment]
The sole goal of javapackages-bootstrap project is to bundle dependencies required by javapackages-tools so that it can be built without reliance on system packages. This request doesn't make sense.
