### ISSUE TITLE
Handle licence linstallation filename conflicts

### ISSUE THREAD

**Issue by terminus-brut** [fedora-java/javapackages-bootstrap#15]
In order to be more foolproof the tool should handle situations when:
1. the component already has a file named COPYING and it is also necessary to extract license text
2. it is necessary to extract multiple license texts.

The simplest solution i see is for both problems is:
* for problem 1) add `StandardOpenOption.APPEND` to code which copies over the license text
* for problem 2) manually concatenate the text in `<text>` field if there is a need to

**Comment by mizdebsk** [comment]
For problem 1. I would simply fail the build.
Until problem 2. arises I would not do anything.

**Comment by terminus-brut** [comment]
Failing the build is also a viable option.
The most important thing is to avoid silent text replacements.
