### ISSUE TITLE
Make -incremental builds also rebuild all the dependent projects

### ISSUE THREAD

**Issue by mkoncek** [fedora-java/javapackages-bootstrap#65]
Updating a lower level library which is used as a compile dependency for other projects requires doing a full rebuild to ensure that the dependent projects compile with the new version of the library.
AFAIK `-incremental` build only builds parts which are missing. I believe it should rebuild all the dependent projects as well.
I tested this by removing `slf4j` from `build/` and running `-incremental`. Only `slf4j` was rebuilt.

**Comment by mizdebsk** [comment]
Agreed, it would be nice to implement this.

**Comment by mizdebsk** [comment]
@mkoncek PR that addresses your request is available.
Please test if the new behavior is what you expected.
